services:
  lich-server:
    build:
      context: ./lich-server
      dockerfile: Dockerfile
    container_name: lich-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lich-server.rule=Host(`${DOMAIN:?DOMAIN is required. Set it in .env}`)"
      - "traefik.http.routers.lich-server.entrypoints=websecure"
      - "traefik.http.routers.lich-server.tls.certresolver=myresolver"
      - "traefik.http.services.lich-server.loadbalancer.server.port=3000"
    volumes:
      - ./data:/data
    env_file:
      - .env.docker # make sure to copy .env.example and named it .env.docker!
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      TRUST_PROXY: "true"
    networks:
      - traefik_default
    restart: unless-stopped

networks:
  traefik_default:
    external: true
