services:
  lich-server:
    build:
      context: ./lich-server
      dockerfile: Dockerfile
    image: lich-server:latest
    container_name: lich-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lich.rule=Host(`${DOMAIN:-lich.codechovui.dev}`)"
      - "traefik.http.routers.lich.entrypoints=websecure"
      - "traefik.http.routers.lich.tls.certresolver=myresolver"
      - "traefik.http.services.lich.loadbalancer.server.port=3000"
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    networks:
      - traefik_default
    restart: unless-stopped

networks:
  traefik_default:
    external: true
